-- ── Core ──────────────────────────────────────────────────────────────────

Revenue =
SUMX(
    'public sales',
    'public sales'[quantity] * 'public sales'[unit_price]
)

Units Sold =
SUM('public sales'[quantity])

Avg Order Value =
DIVIDE([Revenue], COUNTROWS('public sales'))

Products Sold =
DISTINCTCOUNT('public sales'[product_name])

Revenue % of Total =
DIVIDE(
    [Revenue],
    CALCULATE([Revenue], ALL('public sales'))
)

-- ── Time Intelligence (requires dim_date marked as Date Table) ────────────

Revenue YTD =
TOTALYTD(
    [Revenue],
    'public dim_date'[date]
)

Units Sold YTD =
TOTALYTD(
    [Units Sold],
    'public dim_date'[date]
)

Revenue Prior Month =
CALCULATE(
    [Revenue],
    DATEADD('public dim_date'[date], -1, MONTH)
)

Revenue MoM Change =
[Revenue] - [Revenue Prior Month]

Revenue Growth % =
DIVIDE(
    [Revenue MoM Change],
    [Revenue Prior Month]
)

Revenue Prior Year =
CALCULATE(
    [Revenue],
    SAMEPERIODLASTYEAR('public dim_date'[date])
)

Revenue YoY Growth % =
DIVIDE(
    [Revenue] - [Revenue Prior Year],
    [Revenue Prior Year]
)

-- ── Rankings ──────────────────────────────────────────────────────────────

Top Product =
CALCULATE(
    SELECTEDVALUE('public sales'[product_name]),
    TOPN(1, VALUES('public sales'[product_name]), [Revenue], DESC)
)

Top Category =
CALCULATE(
    SELECTEDVALUE('public sales'[category]),
    TOPN(1, VALUES('public sales'[category]), [Revenue], DESC)
)
